[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "galleries"
  name = "Galleries"
  url = "galleries"
  weight = 3

# TODO: 'archive' currently not handled
#[[main]]
#  identifier = "archive"
#  name = "Archive"
#  url = "archive"
#  weight = 4

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 5

[[main]]
  identifier = "search"
  name = "icon-search"
  url = "search"
  weight = 6