#logoImage = "" # E.g.: "/logo/logo.png"
logoText = "ExampleSite"
logoType = "short" # long, short
description = "MyBlog Theme for Hugo example site."
custom_css = []
custom_js = []
meta_image = ""
#themecolor = "" #TODO: remove (unused)

#TODO: adapt! ('contact'? 'archive' when handled, etc.)
notAllowedTypesInHome = ["about", "contact"] # posts types in home page
notAllowedTypesInHomeSidebar = ["about", "search"] # posts types in lists on home page ('top'+'recent')
#notAllowedTypesInArchive #TODO: 'archive' currently not handled
#TODO: If using 'showFeedLinks' - adapt! (look in original Zzo) (+'archive' when handled, etc.)
#notAllowedTypesInHomeFeed = ["about", "contact", "galleries" ]

viewportSize = "wide" # widest, wider, wide, normal, narrow
#enableSideDataLeft = true # Default: false
#enableSideDataRight = true # Default: false

enableUiAnimation = true #TODO: keep? used?
hideSingleContentsWhenJSDisabled = false

mainSections = [ "posts", "galleries" ]

# navbar
enableThemeChange = true
enableLangChange = true

# header
# Examples defined in "content/en/_index.md": "single-image", "single-fixed", "single-ratio", "single-window", "multi".
homeHeaderType = "multi"

# menu
showMobileMenuTerms = ["tags", "categories", "series"] #TODO: change "series" to "types"

# body
# breadcrumb
enableBreadcrumb = true # Default false
breadcrumbHome = "both" # Default "icon", values: "text", "icon", "both"
#breadcrumbHomeSiteName = false # Default true

# single
metaInfoEdit = true
metaInfoReadingTime = true
metaTags = true
enableTocContent = false # TOC in page body
#titleClipboard = true # Default false
codeClipboard = true # Default false

enableGoToTop = true

summaryShape = "tiles" # Default for all pages, values: "card", "classic", "compact", "tiles"
#summaryShapeHome = "tiles" # Default as "summaryShape"
#summaryShapeList = "tiles" # Default as "summaryShape"
#summaryShapeTaxonomy = "classic" # Default as "summaryShape"
showonlyimage = false
summaryMeta = true # Default false
#summaryImagePosition = "left" # Default "left"
#summaryMetaInfoCreate = false # Default true
#summaryMetaInfoEdit = true # Default false
summaryMetaInfoReadingTime = true # Default false
summaryMetaTags = true # Default false
#summaryMetaCategories = true # Default false
#summaryMetaSeries = true # Default false
#summaryDescription = true # Default false


paginateWindow = 1

# thumbnails zoom
#sliderInitZoom = false
sliderZoom = true
tileInitZoom = true
tileZoom = true
summaryInitZoom = true
summaryZoom = false
galleryInitZoom = true
galleryZoom = true

#disableSearchSections = true # Default: false
#disableSearchAuthors = true # Default: false


#TODO: rename all params to "bio..." (+propagate impacts)
# whoami
# Not necessary if no "bio" in sidebars
myname = "Someone"
email = "someone@email.com" #TODO: use same as in "socialOptions" - Duplicate? Remove here?
whoami = "Blogger"
bioImage = "" # Example: "/images/bio/avatar.jpg"
useGravatar = false
location = "City, Country"
organization = "Hugo"
link = "https://somesite.org"

# Sidebar
#TODO: depends on page type! (=> specify!)
# Allowed components: "thumbnail", "bio", "top", "recent", "tags", "categories", "series", "search", custom", "-"
#sidebarHomeLeft = []
sidebarHomeRight = [ "bio", "recent", "-", "tags", "categories", "series", "search" ] #TODO
sidebarSingleLeft = [ "thumbnail", "-", "toc" ] #TODO
#sidebarSingleRight = [ "toc", "tags", "categories", "series", "search" ] #TODO
sidebarSingleRight = [ "-", "tags", "categories", "series", "search" ] #TODO
singleTaxonomies = true # default: false
#sidebarListLeft = [ ... ] #TODO
sidebarListRight = [ "recent", "-", "tags", "categories", "series", "search" ] #TODO
#sidebarTaxonomyLeft = [ "-", "bio" ] #TODO
sidebarTaxonomyRight = [ "-", "tags", "categories", "series", "search" ] #TODO
#sidebarSearchLeft = [ "-", "bio" ] #TODO
#sidebarSearchRight = [ "-", "bio" ] #TODO
#disableSidebarLeft = false # Default: false
#disableSidebarRight = false # Default: false
enableSidebarSeparator = true # Default: true
enableSidebarBio = true # Default: false
enableBioImage = true # Default: true
enableSidebarPostsByOrder = false # Default: false #TODO: rename to "enableTop"?
enableSidebarRecent = true # Default: false
enableSidebarTags = true # Default: false
enableSidebarSeries = true # Default: false
enableSidebarCategories = true # Default: false
enableSidebarSearch = true # Default: false
enableToc = true #TODO: rename to enableSidebarToc
#tocLevels = ["h2", "h3", "h4"] #TODO: seems useless/ignored?
#tocFolding = true # collapse sub titles
itemsPerCategory = 5 #TODO: set 1 for each component? (recent, top, etc.)


# footer
showPoweredBy = true
showFeedLinks = false
showSocialLinks = true

# service
googleTagManager = "" # GTM-XXXXXX #TODO: can comment line if not used?
baiduAnalytics = ""
enableBusuanzi = false
#busuanziSiteUV = true #TODO: uncomment if using Busuanzi
#busuanziSitePV = true #TODO: uncomment if using Busuanzi
#busuanziPagePV = true #TODO: uncomment if using Busuanzi


























































[socialOptions]
  #TODO: Add missing icons!
  email = "mailto:your@email.com"
  phone = ""
  facebook = "http://facebook.com/"
  twitter = "http://twitter.com/"
  github = "https://github.com/2-REC/hugo-myblog-theme"
  #stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  #medium = ""
  #tumblr = ""
  linkedin = ""
  pinterest = ""
  #stack-exchange = ""
  #telegram = ""
  #steam = ""
  #weibo = ""
  #douban = ""
  #csdn = ""
  gitlab = ""
  #mastodon = ""
  #jianshu = ""
  #zhihu = ""
  #signal = ""
  #whatsapp = ""
  #matrix = ""
  #xmpp = ""
  #dev-to = ""
  #gitea = ""
  #google-scholar = ""













# Included: douban, facebook, line, linkedin, reddit, telegram, tumblr, twitter, weibo
[[share]]
  name = "facebook"
  color = "#1877F2"
[[share]]
  name = "linkedin"
  color = "#0077B5"
[[share]]
  name = "reddit"
  color = "#FF4500"
[[share]]
  name = "tumblr"
  color = "#36465D"
[[share]]
  name = "twitter"
  color = "#1DA1F2"
  username = "twitter_user"
[[share]]
  name = "whatsapp"
  color = "#25D366"

# Included: alipay, bitcoin, patreon, paypal, wechat
[[donation]]
  name = "paypal"
  url = ""
[[donation]]
  name = "patreon"
  url = ""
[[donation]]
  name = "wechat"
  url = ""
  qr = true


[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""

# 2-REC: added in example
[copyrightOptions] # Footer
  copyrightLink = "https://github.com/2-REC"
  copyrightOwner = "2-REC"
  copyrightStartYear = "2020"

[slider]
  enable = true
  manual = false # Setting manual to true renders the slide selection to only those where the post has a slide=true option enabled
  num_features = 6 # The slider picks up the banner images from the N most recent posts, where num_features is N.
  transition_effect = "fade" # Possible values: blindX, blindY, blindZ, cover, curtainX, curtainY, fade, fadeZoom, growX, growY, none, scrollUp, scrollDown, scrollLeft, scrollRight, scrollHorz, scrollVert, shuffle, slideX, slideY, toss, turnUp, turnDown, turnLeft, turnRight, uncover, wipe, zoom
  transition_delay = 4000 # ms
  transition_duration = 1000 # ms
